services:
  public:
    build: .
    command: npm run dev
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      # Map the source file specifically to the host
      - ./src/assets/games.json:/app/src/assets/games.json

  admin:
    build: .
    command: npm run dev:admin
    ports:
      - "5174:5173"
    restart: unless-stopped
    volumes:
      - ./src/assets/games.json:/app/src/assets/games.json